#---
#spring:
#  application:
#    name: microservice-eureka-server
#  profiles: peer1
#server:
#  port: 8761
#eureka:
#  instance:
#    hostname: eureka-server-peer1
#  server:
#    enable-self-preservation: false #关闭自我保护
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-server-peer2:8762/eureka/
#
#---
#spring:
#  application:
#    name: microservice-eureka-server
#  profiles: peer2
#server:
#  port: 8762
#eureka:
#  instance:
#    hostname: eureka-server-peer2
#  server:
#    enable-self-preservation: false #关闭自我保护
#  client:
#    registerWithEureka: false
#    fetchRegistry: false
#    serviceUrl:
#      defaultZone: http://eureka-server-peer1:8761/eureka/



##################本地配置###################
spring:
  application:
    name: microservice-eureka-server
server:
  port: 8761
eureka:
  instance:
    hostname: localhost
  server:
    enable-self-preservation: false #关闭自我保护
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
